name 'zookeeper'
maintainer 'arreyder'
maintainer_email 'YOUR_EMAIL'
license 'All rights reserved'
description 'Installs/Configures zk'
long_description 'Installs/Configures zk'
version '0.0.8'

depends 'yum'
depends 'yum-epel'
depends 'runit'
depends 'java'
depends 'ark'
depends 'base'
depends 'iptables'
depends 'elk-wrapper'
